// <auto-generated />
using System;
using AutoDevRunner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoDevRunner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709144718_AddRunMetrics")]
    partial class AddRunMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoDevRunner.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiBranchPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AllowAiEditBrief")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowRunOnMainBranch")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoCommit")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoPush")
                        .HasColumnType("boolean");

                    b.Property<string>("BriefPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentBranch")
                        .HasColumnType("text");

                    b.Property<string>("CurrentTask")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("LastProvider")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRunStatus")
                        .HasColumnType("text");

                    b.Property<string>("LastSummary")
                        .HasColumnType("text");

                    b.Property<int>("MaxRunMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectType")
                        .HasColumnType("text");

                    b.Property<string>("ProviderPriority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderSessionId")
                        .HasColumnType("text");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationCommand")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AutoDevRunner.Models.ProjectBrief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Version")
                        .IsUnique();

                    b.ToTable("ProjectBriefs");
                });

            modelBuilder.Entity("AutoDevRunner.Models.ProviderState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAuthErrorAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastKnownUsage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastQuotaLimitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastQuotaResetHint")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("ProviderStates");
                });

            modelBuilder.Entity("AutoDevRunner.Models.RunRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("ChangedFiles")
                        .HasColumnType("text");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("CreativePlan")
                        .HasColumnType("text");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("LogPath")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<bool?>("NotVerified")
                        .HasColumnType("boolean");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<int?>("PromptChars")
                        .HasColumnType("integer");

                    b.Property<int?>("PromptEstTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("RepairAttempts")
                        .HasColumnType("integer");

                    b.Property<bool?>("Resumed")
                        .HasColumnType("boolean");

                    b.Property<string>("Risk")
                        .HasColumnType("text");

                    b.Property<string>("SessionResult")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TaskSource")
                        .HasColumnType("text");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.Property<string>("Usage")
                        .HasColumnType("text");

                    b.Property<bool?>("ValidationInferred")
                        .HasColumnType("boolean");

                    b.Property<string>("ValidationOutput")
                        .HasColumnType("text");

                    b.Property<bool>("ValidationPassed")
                        .HasColumnType("boolean");

                    b.Property<bool>("ValidationRun")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("AutoDevRunner.Models.ProjectBrief", b =>
                {
                    b.HasOne("AutoDevRunner.Models.Project", "Project")
                        .WithMany("Briefs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AutoDevRunner.Models.RunRecord", b =>
                {
                    b.HasOne("AutoDevRunner.Models.Project", "Project")
                        .WithMany("Runs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AutoDevRunner.Models.Project", b =>
                {
                    b.Navigation("Briefs");

                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
