using System.Text;

namespace AutoDevOrchestrator;

/// <summary>Writes docs/autodev/NEXT_IMPLEMENTER_PROMPT.md — the deterministic handoff to Claude CLI / Codex.</summary>
public static class ImplementerPromptWriter
{
    public static string? WriteNextTaskPrompt(RepoPaths paths, OrchestratorConfig config, PlanDocument plan)
    {
        var task = plan.PendingTasks.FirstOrDefault();
        if (task is null) return null;

        var appFullPath = config.GardenAppFullPath(paths);
        var appExists = Directory.Exists(appFullPath);
        var packageJson = Path.Combine(appFullPath, "package.json");
        var hasNpm = File.Exists(packageJson);

        var sb = new StringBuilder();
        sb.AppendLine("# Next Implementer Task — Daily Pixel Garden");
        sb.AppendLine();
        sb.AppendLine($"> Generated by autodev-orchestrator on {DateTime.Now:yyyy-MM-dd HH:mm}. " +
                      "This file is the handoff from the OpenAI Creative Director to the code implementer " +
                      "(Claude CLI / Codex / autodev). Execute exactly one task, then update the status files.");
        sb.AppendLine();

        sb.AppendLine("## Project context");
        sb.AppendLine();
        sb.AppendLine("- Daily Pixel Garden is a cozy pixel-art web world (Angular + PixiJS) that grows a little every day.");
        sb.AppendLine($"- The garden app lives at `{config.GardenAppRelPath}`" +
                      (appExists ? "." : " — **it does not exist yet; this task may include creating it.**"));
        sb.AppendLine($"- Current plan: `docs/autodev/CURRENT_PLAN.json` (date {plan.PlanDate}, theme: \"{plan.Theme}\").");
        sb.AppendLine($"- Creative direction: {plan.CreativeDirection}");
        if (plan.Constraints.Count > 0)
        {
            sb.AppendLine("- Plan constraints:");
            foreach (var constraint in plan.Constraints) sb.AppendLine($"  - {constraint}");
        }
        sb.AppendLine();

        sb.AppendLine($"## Task {task.Id}: {task.Title}");
        sb.AppendLine();
        sb.AppendLine($"- Type: {task.Type} | Priority: {task.Priority} | Size: {task.EstimatedSize}");
        sb.AppendLine();
        sb.AppendLine("### Implementation prompt");
        sb.AppendLine();
        sb.AppendLine(task.ImplementationPrompt);
        sb.AppendLine();
        sb.AppendLine("### Acceptance criteria");
        sb.AppendLine();
        foreach (var criterion in task.AcceptanceCriteria) sb.AppendLine($"- [ ] {criterion}");
        sb.AppendLine();

        sb.AppendLine("## Files likely to inspect");
        sb.AppendLine();
        sb.AppendLine("- `docs/autodev/CURRENT_PLAN.json` — full plan and task statuses");
        sb.AppendLine("- `docs/autodev/DAILY_LOG.md` — story so far");
        sb.AppendLine(appExists
            ? $"- `{config.GardenAppRelPath}/` — the app (start with `src/`, `package.json`, the main Pixi scene component)"
            : $"- `{config.GardenAppRelPath}/` — to be created (keep it a minimal Angular workspace with a PixiJS canvas)");
        sb.AppendLine();

        sb.AppendLine("## Verification");
        sb.AppendLine();
        if (hasNpm)
        {
            sb.AppendLine($"Run inside `{config.GardenAppRelPath}`:");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine("npm install");
            sb.AppendLine("npm run build");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("Run `npm test` only if a test script is defined in package.json.");
        }
        else
        {
            sb.AppendLine("The garden app has no package.json yet. After scaffolding, `npm install` and `npm run build` " +
                          $"must succeed inside `{config.GardenAppRelPath}`. Do not invent other commands.");
        }
        sb.AppendLine();
        sb.AppendLine("Then start the dev server, open the app in a browser, and confirm the acceptance criteria " +
                      "and that the console has no errors.");
        sb.AppendLine();

        sb.AppendLine("## After completion (required)");
        sb.AppendLine();
        sb.AppendLine($"1. In `docs/autodev/CURRENT_PLAN.json`, set task `{task.Id}` `\"status\"` to `\"completed\"` " +
                      "and `\"completed_at\"` to the current ISO timestamp. If the task turned out infeasible, " +
                      "set `\"skipped\"` instead and explain why in the daily log.");
        sb.AppendLine("2. Append a short dated entry to `docs/autodev/DAILY_LOG.md` describing what changed in the garden " +
                      "(one or two cozy sentences plus a technical note).");
        sb.AppendLine("3. Do not start other tasks, do not call OpenAI, do not edit `docs/autodev/plans/` history. Keep the change small.");

        File.WriteAllText(paths.NextImplementerPromptFile, sb.ToString());
        return task.Id;
    }
}
